name: 🐛 Bug / Crash Report
description: Create a bug or crash report for Vesktop
labels: [bug]
title: "[Bug] <title>"

body:
    - type: markdown
      attributes:
          value: |
              **Thanks 🩷 for taking the time to fill out this bug report! Before proceeding, please read the following**

              Make sure a similar issue doesn't already exist by [searching the existing issues](https://github.com/Vencord/Vesktop/issues?q=is%3Aissue) for keywords!

              Make sure both Vesktop and Vencord are fully up to date. You can update Vencord by right-clicking the Vesktop tray icon and pressing "Repair Vencord"

              **DO NOT REPORT** any of the following issues:
              - Purely graphical glitches like flickering, scaling issues[^1]
              - App crashing / not showing window with mentions of the gpu process in the stacktrace[^1]
              - Screenshare not starting, black screening or crashing[^2]
              - Vencord related issues: This is the Vesktop repo, not Vencord
              - Captchas[^3]
              - Issues with opening URLs[^4]
              - Issues with Notifications[^4]
              - Issues with Input Methods[^4]
              - Issues with File Drag and Drop[^5] 
              - Network Errors[^6]

              Linux users: Please only report issues with supported packages (flatpak and any builds from the README / releases).
              We do not support other packages, like the AUR or Nix packages, so please first make sure your issue is reproducible with official releases,
              like [our Flatpak](https://flathub.org/apps/dev.vencord.Vesktop) or [AppImage](https://vencord.dev/download/vesktop/amd64/appimage)


              [^1]: GPU issue. Disable hardware acceleration in Vesktop Settings or run with `--disable-gpu`
              [^2]: System issue. You will have to fix it
              [^3]: If you are receiving a lot of captchas, it means Discord thinks you might be a bot. Make sure you're not using a VPN/Proxy
              [^4]: These things are handled by Chromium / Electron, not us. If they don't work, it's either an issue with your system or a bug with Chromium.
              [^5]: You are likely using the Vesktop flatpak and trying to drop a file the flatpak can't access. You can fix this by installing Flatseal and using it to grant Vesktop full access to your files
              [^6]: Issue on your end, you have to fix it. Try changing your DNS to [1.1.1.1 (Cloudflare DNS)](https://developers.cloudflare.com/1.1.1.1/setup/)
              
    - type: input
      id: discord
      attributes:
          label: Discord Account
          description: Who on Discord is making this request? Not required but encouraged for easier follow-up
          placeholder: username#0000
      validations:
          required: false

    - type: input
      id: os
      attributes:
          label: Operating System
          description: What operating system are you using (eg Windows 10, macOS Big Sur, Ubuntu 20.04)?
          placeholder: Windows 10
      validations:
          required: true

    - type: input
      id: linux-de
      attributes:
          label: Linux Only ~ Desktop Environment
          description: If you are on Linux, what Desktop environment are you using (eg GNOME, KDE, XFCE)? Are you using Wayland or Xorg?
          placeholder: Gnome on Wayland
      validations:
          required: false

    - type: input
      id: install-type
      attributes:
          label: Package Type
          description: What kind of Vesktop package are you using? (Setup exe, Portable, Flatpak, AppImage, Deb, etc)
          placeholder: Flatpak
      validations:
          required: true

    - type: textarea
      id: bug-description
      attributes:
          label: What happens when the bug or crash occurs?
          description: Where does this bug or crash occur, when does it occur, etc.
          placeholder: The bug/crash happens sometimes when I do ..., causing this to not work/the app to crash. I think it happens because of ...
      validations:
          required: true

    - type: textarea
      id: expected-behaviour
      attributes:
          label: What is the expected behaviour?
          description: Simply detail what the expected behaviour is.
          placeholder: I expect Vencord/Discord to open the ... page instead of ..., it prevents me from doing ...
      validations:
          required: true

    - type: textarea
      id: steps-to-take
      attributes:
          label: How do you recreate this bug or crash?
          description: Give us a list of steps in order to recreate the bug or crash.
          placeholder: |
              1. Do ...
              2. Then ...
              3. Do this ..., ... and then ...
              4. Observe "the bug" or "the crash"
      validations:
          required: true

    - type: textarea
      id: debug-logs
      attributes:
          label: Debug Logs
          description: Run vesktop from the command line. Include the relevant command line output here. If there are any lines that seem relevant, try googling them or searching existing issues
          value: |
              ```
              Replace this text with your crash-log. Do not remove the backticks
              ```
      validations:
          required: true

    - type: checkboxes
      id: agreement-check
      attributes:
          label: Request Agreement
          description: We only accept reports for bugs that happen on supported and up to date Vesktop releases
          options:
              - label: I have searched the existing issues and found no similar issue
                required: true
              - label: I am using the latest Vesktop and Vencord versions
                required: true
              - label: This issue occurs on an official release (not just the AUR or Nix packages)
                required: true
