name: Build Vesktop Pacman Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libarchive-tools
        npm install -g pnpm

    - name: Install pnpm dependencies
      run: pnpm install

    - name: Build Pacman package
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: pnpm package --linux pacman --publish never

    - name: Delete old artifacts
      uses: actions/github-script@v5
      with:
        script: |
          const artifacts = await github.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          for (const artifact of artifacts.data.artifacts) {
            // Keep only the latest one
            if (artifact.name !== 'vesktop-package' || artifact.updated_at < artifacts.data.artifacts[0].updated_at) {
              await github.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              });
            }
          }

    - name: Upload Pacman package artifact
      uses: actions/upload-artifact@v3
      with:
        name: vesktop-package
        path: dist/*.pacman
